### ISSUE TITLE
about representations of intra-modality & inter-modality 

### ISSUE THREAD

**Issue by Leo-Repo** [jefferyYu/TomBERT#3]
Hi author,
I'm confused about the representations of "intra-modality dynamics including target-text and target-image alignments and inter-modality dynamics, i.e., text-image alignments" mentioned in the paper. In my opinion, intra-modality dynamics should refer to what happened between the same modality, such as text to text rather than target (text) -image, similarly inter-modality dynamics should refer to what happened between the different modality, such as text-image.  So, is there something that I ignored?
Thank you for your trouble!

**Comment by jefferyYu** [comment]
Hi there,

Thanks for your good question!

Yes, your understanding about intra-modality dynamics and inter-modality dynamics is correct. In this paper, because target refers to the opinion target term without any textual context, we did not treat it as either text or image modality (although it is indeed part of the text modality). Instead, we regard it as auxiliary information to textual and visual features. The output of the target-text interaction is still considered as the text modality whereas the output of the target-image interaction is still considered as the image modality. Hence, we call target-text and target-image as intra-modality dynamics.

Hope it clarifies your confusion.
